[project]
name = "2026-python-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.139.0",
    "02-data-analysis",
    "03-web-crawer-learning",
]

[tool.uv.sources]
02-data-analysis = { workspace = true }
03-web-crawer-learning = { workspace = true }

# 宣告工作區包含所有子資料夾
[tool.uv.workspace]
members = ["*"]
