[project]
name = "03-web-crawer-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pmake", email = "pmake@users.noreply.github.com" }
]
requires-python = ">=3.12.13"
dependencies = [
    "requests>=2.32.5",
    "beautifulsoup4>=4.15.0",
    "lxml>=6.1.1",
    "pandas>=3.0.3",
    "openpyxl>=3.1.5",
    "playwright>=1.62.0",
    "cloakbrowser>=0.5.5",
    "pyperclip>=1.11.0",
]

[build-system]
requires = ["uv_build>=0.11.28,<0.13.0"]
build-backend = "uv_build"
