[project]
name = "02-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pmake", email = "pmake@users.noreply.github.com" }
]
requires-python = ">=3.12.13"
dependencies = [
    "pandas>=3.0.3",
    "python-dotenv>=1.2.2",
    "supabase>=2.31.0",
]

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"
